network:
        version: 2
        renderer: NetworkManager
        bridges:
                inetsim:
                        dhcp4: no
                        dhcp6: no
                        accept-ra: no
                        interfaces: []
                        addresses:
                                - 192.168.124.1/24
